[versions]
project-packageName = "io.ma7moud3ly.nemo"
project-vendor = "github.com/Ma7moud3ly"
project-versionCode = "1"
project-versionName = "1.0.3"
android-compileSdk = "37"
android-targetSdk = "37"
android-minSdk = "23"
#plugins
agp = "9.3.2"
kotlin = "2.4.10"
composeHotReload = "1.2.0"
composeMultiplatform = "1.12.0"
kotlinSerialization = "2.4.10"
mavenPublish = "0.37.0"
#common
ui = "1.12.0"
uiToolingPreview = "1.12.0"
uiTooling = "1.12.0"
runtime = "1.12.0"
lifecycle-runtime = "2.11.0"
kotlinx-coroutines = "1.11.0"
navigation-compose = "2.9.2"
serialization-json = "1.11.0"
componentsResources = "1.12.0"
foundation = "1.12.0"
material3 = "1.9.0"
materialIconsExtended = "1.7.3"
kotlinxDatetime = "0.8.0"
adaptive = "1.2.0"
filekit = "0.15.0"
multiplatformSettings = "1.3.0"
#android
androidx-core = "1.19.0"
androidx-activity = "1.13.0"
firebaseBom = "34.18.0"
googleServices = "4.5.0"
firebaseCrashlytics = "3.0.8"

[libraries]
components-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "componentsResources" }
foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "foundation" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }

ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "ui" }
ui-tooling = { module = "org.jetbrains.compose.ui:ui-tooling", version.ref = "uiTooling" }
ui-tooling-preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "uiToolingPreview" }
runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "runtime" }

lifecycle-viewmodel-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle-runtime" }
lifecycle-runtime-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle-runtime" }
kotlinx-coroutinesSwing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }

androidx-navigation = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "navigation-compose" }
material-icons-extended = { module = "org.jetbrains.compose.material:material-icons-extended", version.ref = "materialIconsExtended" }
material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "material3" }
material3-adaptive = { module = "org.jetbrains.compose.material3.adaptive:adaptive", version.ref = "adaptive" }
kotlinx-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization-json" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
# file picker
filekit-core = { module = "io.github.vinceglb:filekit-core", version.ref = "filekit" }
filekit-dialogs = { module = "io.github.vinceglb:filekit-dialogs", version.ref = "filekit" }
# prefrences
settings-noArg = { module = "com.russhwolf:multiplatform-settings-no-arg", version.ref = "multiplatformSettings" }
#Android
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-core = { module = "androidx.core:core", version.ref = "androidx-core" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-analytics-ktx = { module = "com.google.firebase:firebase-analytics" }
firebase-crashlytics-ktx = { module = "com.google.firebase:firebase-crashlytics" }

[plugins]
androidKotlinMultiplatformLibrary = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
composeHotReload = { id = "org.jetbrains.compose.hot-reload", version.ref = "composeHotReload" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlinSerialization" }
#android
androidApplication = { id = "com.android.application", version.ref = "agp" }
google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebaseCrashlytics" }
#maven
vanniktech-maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "mavenPublish" }
